# Generated by Django 4.2.3 on 2023-07-04 10:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary_app', '0003_alter_diaryentry_entry_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diaryentry',
            name='entry_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
