# Generated by Django 4.2.3 on 2023-07-04 10:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('diary_app', '0004_alter_diaryentry_entry_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diaryentry',
            name='entry_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
